# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdlH-MvgkOlWQQF0vszTNXZSoidY0eva
"""

# borehole_app.py

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Borehole Data Analysis", layout="wide")

# -----------------------
# Load data
# -----------------------
@st.cache_data
def load_data(file):
    return pd.read_excel(file)

st.title("⛏️ Borehole Data Analysis App")

uploaded_file = st.file_uploader("📂 Upload Borehole Excel (91 BH dataset)", type=["xlsx"])

if uploaded_file is not None:
    df = load_data(uploaded_file)

    # Standardize column names
    df.columns = df.columns.str.strip().str.lower()

    # Expecting columns like: Borehole | Lithology | Length | Al2O3 | SiO2
    st.success("✅ Data loaded successfully!")

    # -----------------------
    # Page Navigation
    # -----------------------
    page = st.sidebar.radio("📑 Select Page", ["Borehole Selection", "Lithology Breakdown", "Overall Quality"])

    # -----------------------
    # Page 1: Borehole Selection
    # -----------------------
    if page == "Borehole Selection":
        st.header("🔎 Select Borehole(s)")
        boreholes = df['borehole'].unique()
        selected_bhs = st.multiselect("Choose Borehole(s):", boreholes)

        if selected_bhs:
            st.write("### Selected Boreholes Data")
            st.dataframe(df[df['borehole'].isin(selected_bhs)])

    # -----------------------
    # Page 2: Lithology Breakdown
    # -----------------------
    elif page == "Lithology Breakdown":
        st.header("🪨 Lithology Breakdown")
        boreholes = df['borehole'].unique()
        selected_bhs = st.multiselect("Choose Borehole(s) for Lithology:", boreholes)

        if selected_bhs:
            subset = df[df['borehole'].isin(selected_bhs)]

            litho_summary = subset.groupby("lithology").agg(
                total_meterage=("length", "sum"),
                avg_al2o3=("al2o3", "mean"),
                avg_sio2=("sio2", "mean")
            ).reset_index()

            st.write("### Lithology Summary")
            st.dataframe(litho_summary)

    # -----------------------
    # Page 3: Overall Quality
    # -----------------------
    elif page == "Overall Quality":
        st.header("📊 Overall Quality of Selected Boreholes")
        boreholes = df['borehole'].unique()
        selected_bhs = st.multiselect("Choose Borehole(s) for Overall Quality:", boreholes)

        if selected_bhs:
            subset = df[df['borehole'].isin(selected_bhs)]

            # Weighted averages based on length
            total_length = subset['length'].sum()
            weighted_al2o3 = (subset['al2o3'] * subset['length']).sum() / total_length
            weighted_sio2 = (subset['sio2'] * subset['length']).sum() / total_length

            st.metric("Total Meterage", f"{total_length:.2f} m")
            st.metric("Weighted Avg Al₂O₃", f"{weighted_al2o3:.2f} %")
            st.metric("Weighted Avg SiO₂", f"{weighted_sio2:.2f} %")

else:
    st.info("👆 Please upload your Borehole dataset (Excel) to continue.")

!pip install streamlit